### ISSUE TITLE
[Feature] Decouple this from Fabric

### ISSUE THREAD

**Issue by Rattlyy** [xpple/BetterConfig#3]
Would be great to be able to use this in Paper & Velocity mods. As there's nothing that's fabric-locked like mixins etc, it's an easy thing to do. Would work on it if given an ok.

**Comment by xpple** [comment]
This mod relies heavily on Brigadier, which Paper doesn't currently support. It's in the works, though: [PaperMC#8235](https://github.com/PaperMC/Paper/pull/8235). I am willing to test this new Paper API to see what it can and I'll let you know if it's capable enough to use in BetterConfig. That said, Paper (Bukkit) already has a config system of its own, what in particular do you think that system lacks?

**Comment by xpple** [comment]
Could you join [my Discord server](https://discord.xpple.dev) to discuss this a bit?
