### ISSUE TITLE
[Feature] onChange event

### ISSUE THREAD

**Issue by erxson** [xpple/BetterConfig#4]
It would be cool if you made an event to track changes to any specific config value. 
I know that I can do it myself with my own setter, but a superduper annotation would probably be more convenient.
(translated with google)

**Comment by xpple** [comment]
Is the linked PR what you had in mind (see [this example](https://github.com/xpple/BetterConfig/blob/984f6a656d2d2d3a5d444c0326a9b70e06f600bc/fabric/src/testmod/java/dev/xpple/betterconfig/Configs.java#L90-L94))?
